<?php
header('Access-Control-Allow-Origin: *');
require_once "../../../bootstrap.php";

$taskId = (int) $_POST['taskId'];

$finance = $financeController->get($taskId)->setTimeController($timeController);
$stage = $finance->getStage();

switch ($stage){
    case '0':
        $pictureStr = $_POST['picture'];
        $fileName = null;
        if ($pictureStr!=null){
            $fileName = Controller\Picture\TransferPicture::transfer($pictureStr, '');
        }

        $financeManager = $userController->get((int) $_POST['financeManager']);

        $finance->setPicture($fileName)
            ->setURL($_POST['url'])
            ->setFinanceManager($financeManager)
            ->updateStage('1', $finance->getSeller()->getFullName());

        $taskController->create($financeManager, $taskListController->get(Entity\TaskList::FINANCE), $finance->getId());

        $push->push("You have a new Finance task!", $financeManager->getToken());
        break;

    case '1':
        $finance->updateStage('2', $finance->getFinanceManager()->getFullName());

        $push->push("Finance task $taskId has been approved by finance manager!", $finance->getSeller()->getToken());
        break;

    case '2':
        if ($_POST['action']==='accept'){
            $finance->updateStage('3', $finance->getSeller()->getFullName())
                ->setBankName($_POST['bankName']);

            $push->push("You have a new Finance task!", $finance->getAccounting()->getToken());

            /** @var \Entity\Selling $selling */
            if (($selling = $finance->getSelling()) !== null ){
                if ($selling->getResourceType() === 'Wholesale' || $selling->getResourceType() === 'Auction'){
                    $selling->setTimeController($timeController)
                        ->updateStage('4', "Auto generated by Paperwork task- last step finished by {$finance->getSeller()->getFullName()}");

                    $push->push("Selling task $taskId has been updated by accountant!", $selling->getManager()->getToken());
                }
                else{
                    $selling->setTimeController($timeController)
                        ->updateStage('8', "Auto generated by Paperwork task- last step finished by {$finance->getSeller()->getFullName()}");

                    $push->push("Selling task $taskId has been updated by accountant!", $selling->getSales()->getToken());
                }
                $push->pushWithNotice("Finance for Selling {$selling->getId()} has been approved by bank", $finance->getSeller(), $selling->getManager());
            }
        }
        else{
            $finance->updateStage('6', $finance->getSeller()->getFullName());

            $push->pushWithNotice("Finance task $taskId has been rejected by seller!", $finance->getSeller(), $finance->getManager());
        }
        break;

    case '3':
        $finance->updateStage('4', $finance->getAccounting()->getFullName());

        $push->pushWithNotice("Finance task $taskId is complete!", $finance->getAccounting(), $finance->getSeller());
        break;
}
$entityManager->flush();