<?php
header('Access-Control-Allow-Origin: *');
require_once "../../../bootstrap.php";

$paper = $paperworkController->get((int) $_POST['taskId'])->setTimeController($timeController);
$id = $paper->getId();
$stage = $paper->getStage();

switch ($stage){
    case '0':
        if ($_POST['action']==='accept'){
            $paper->updateStage('1', $paper->getManager()->getFullName())
                ->setFrontDesk($userController->get((int) $_POST['frontDesk']));

            $taskController->create($paper->getFrontDesk(), $taskListController->get(Entity\TaskList::PAPERWORK), $paper->getId());

            $push->push("You have a new paperwork!", $paper->getSeller()->getToken());
        }
        else{
            $paper->updateStage('4', $paper->getManager()->getFullName());
        }
        break;

    case '1':
        if ($_POST['action']==='accept'){
            $paper->updateStage('2', $paper->getSeller()->getFullName());

            $push->push("You have a new Paperwork!", $paper->getFrontDesk()->getToken());
            $push->pushWithNotice("Paperwork $id has been updated by front desk!", $paper->getSeller(), $paper->getManager());
        }
        else{
            $paper->updateStage('4', $paper->getSeller()->getFullName());

            $push->pushWithNotice("Paperwork $id has been closed by front desk!", $paper->getFrontDesk(), $paper->getManager());
        }
        break;

    case '2':
        $paper->updateStage('3', $paper->getFrontDesk()->getFullName())
            ->setTracking($_POST['tracking'])
            ->setPickUp($_POST['pickUp']);

        $push->push("Paperwork $id has been updated by front desk!", $paper->getSeller()->getToken());
        break;

    case '3':
        $paper->updateStage('4', $paper->getSeller()->getFullName());

        $push->pushWithNotice("Paperwork $id is complete", $paper->getSeller(), $paper->getManager());
        $push->pushWithNotice("Paperwork $id is complete", $paper->getSeller(), $paper->getFrontDesk());

        /** @var \Entity\Selling $selling */
        if (($selling = $paper->getSelling()) !== null ){
            $selling->setTimeController($timeController)
                ->updateStage('11', "Auto generated by Paperwork task- last step finished by {$paper->getSeller()->getFullName()}");

            $push->pushWithNotice("Paperwork for Selling {$selling->getId()} is done", $paper->getSeller(), $selling->getManager());

            // TODO: update to stage 10 if car is consignment
            if ($selling->getCar()){

            }
        }
        break;
}
$entityManager->flush();